### ISSUE TITLE
Make width of left column adjustable in trace detail view

### ISSUE THREAD

**Issue by tiffon** [uber/jaeger-ui#63]
The width of the left column in the trace detail view can be made adjustable to accommodate deeply nested spans, e.g. the same way the width of a column in a table can be adjusted.

![span-name-truncation-marked](https://user-images.githubusercontent.com/2304337/29518595-fae7fc82-8647-11e7-9eff-5069b85160d6.png)

**Comment by jcorbin** [comment]
My two cents: changeable width with more obvious truncation and a tooltip seems a more usual/usable choice here than scrolling horizontally within such a column (per #62). By "obvious" I mean using an ellipsis so it reads more like "serviceName reallyLongEndpoi...", or at worst "reallyLongServi..." I suppose?

**Comment by yurishkuro** [comment]
I agree, we should not make it scrollable, it's just bad usability. I'd start with ellipsis and tooltip, and if people still complain revisit making the width adjustable (unless it's easy to do then do both).

I suggest we close #62

**Comment by tiffon** [comment]
Thanks @jcorbin, @yurishkuro for the comments.

The ellipsis has been shown with truncated text (currently in master) and the absence is a regression, which is now resolved in the branch I'm working on. Thanks for pointing it out :+1:

In PR #53, I've added the full service and operation as a tooltip via the `title` attribute. It takes a second for it to come up. As an alternative, I can have the full text show on mouse-over and bleed into the right column (with a background added to it). The nice thing about that is a) it can be triggered without delay and b) it leverages the text that is already showing. What do you think? 

Choosing between the left column being scrollable vs adjustable, I agree, adjustable is better. But, both is better still, so I vote for that with the caveat of seeing where things land when shifting to [react-virtualized](https://github.com/bvaughn/react-virtualized).

**Comment by jcorbin** [comment]
I'm +1 on expanding the text on mouseover rather than a classic tooltip, primarily because that then allows the user to easily select and copy the full name.

I'm still not supportive of adding (even more?) scrollable sub-regions to an already busy visualization like this. To me it's a similar UX sin to nesting and proliferation of tabs. That said, it's not a hill I'm looking to die on, so if you feel strongly that scrolling is a good thing here, I'll wait to see it before final judgement ;-)

**Comment by tiffon** [comment]
Re expanding text on mouse over: Sounds good to me.

@jcorbin - Re scrollbars: To me not having them for the left column seems like a massive omission. We can remove them if they seem sinful when / if added, though.
